version: "2"
services:
    db:
        image: postgres:12
        container_name: spotlight-db
        ports:
        - "5432:5432"
        volumes:
        - db-data:/var/lib/postgresql/data      
        environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: spotlight
         POSTGRES_DB: postgres
    pgadmin:
        depends_on:
        - db
        image: dpage/pgadmin4
        container_name: spotlight-db-admin
        ports:
        - "5050:5050"
        environment:
         PGADMIN_DEFAULT_EMAIL: postgres@localhost
         PGADMIN_DEFAULT_PASSWORD: spotLight
         PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
         PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10 
volumes:
  db-data:
    driver: local